apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-repository-deployment
  labels:
    app: example-repository
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-repository
  template:
    metadata:
      labels:
        app: example-repository
    spec:
      containers:
        - name: example-repository
          image: rvitamin/example-repository:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080