apiVersion: v1
kind: Service
metadata:
  name: example-repository-service
spec:
  type: LoadBalancer
  selector:
    app: example-repository
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080